site_name: Lynx's Blog
site_description: feedId:72571722783979520+userId:42117541714060288
site_url: https://wlynxg.github.io/blog/
repo_name: wlynxg/blog
repo_url: https://github.com/wlynxg/

# Theme
theme:
  name: material
  custom_dir: overrides
  language: 'zh'
  highlightjs: true
  hljs_style: foundation
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - navigation.tabs
    - navigation.instant
    - search.highlight
    - search.suggest
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'


# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

plugins: 
  - search
  - rss:
      enabled: True
      image: https://avatars.githubusercontent.com/u/48609899?v=4
      pretty_print: True
      length: 1000
      date_from_meta:
          as_creation: date.created
          as_update: date.updated
      abstract_chars_count: -1
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true

extra_javascript:
  - https://lib.baomitu.com/babel-polyfill/7.12.1/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js


extra_css:
  - 'from_oi_wiki/css/extra.css?v=13'
  - ../css/neoteroi-mkdocs.css
